spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: payment-service

rabbitmq:
  routing-key:
    payment-notification: payment.notification
  exchange:
    direct: directExchange
