server:
  port: 8060
spring:
  rabbitmq:
    host: localhost
    port: 5672
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    product-url: http://localhost:8222/api/v1/products